/*
 * Fake include file
 */

#include <emu.h>

#ifndef EMU_C
#define EXTERN extern
#else
#define EXTERN
#endif

#define CONTROL EXTERN volatile unsigned short

CONTROL ADC12CTL0;
CONTROL ADC12CTL1;
#define ADC12ENC 1
CONTROL ADC12IE;
CONTROL ADC12IV;
CONTROL ADC12MEM0;
#define ADC12INCH_10 4
#define ADC12INCH_11 8
#define ADC12ON 32
#define ADC12SC 64
#define ADC12SHP 128
#define ADC12SHT0_10 256
#define ADC12SHT0_8 0x200

CONTROL ADC12MCTL0;
#define ADC12SREF_1 0x400

CONTROL AESACTL0;
CONTROL AESADIN_L;
CONTROL AESADOUT_L;
CONTROL AESAKEY_L;
CONTROL AESASTAT;
#define AESBUSY 16
#define AESOP0 32
#define AESOP1 64
#define AESRDYIE 128
#define AESSWRST 256
#define BIT0 (1<<0)
#define BIT1 (1<<1)
#define BIT2 (1<<2)
#define BIT3 (1<<3)
#define BIT4 (1<<4)
#define BIT5 (1<<5)
#define BIT6 (1<<6)
#define BIT7 (1<<7)
#define BIT9 (1<<9)
#define BITA (1<<10)
#define BUSY 1
#define CCIE 2
#define CCIFG 4
#define CHANNR 8
CONTROL CRCDI_L;
/* That beast has hw CRC, AES acceleration?! */
CONTROL CRCINIRES;
#define DCOFFG 64
#define DCORSEL_5 128
CONTROL DEVIATN;
#define ERASE 0x200
#define Eac 0x400
CONTROL FCTL1;
CONTROL FCTL3;
CONTROL FCTL4;
#define FIFOTHR 1
#define FLLD_1 2
CONTROL FOCCFG;
CONTROL FREND0;
CONTROL FREQ0;
CONTROL FREQ1;
CONTROL FREQ2;
CONTROL FSCAL0;
CONTROL FSCAL1;
CONTROL FSCAL2;
CONTROL FSCAL3;
CONTROL FSCTRL1;
CONTROL FWKEY;
CONTROL GIE;
CONTROL LCD4MUX;
CONTROL LCDBBLKCTL;
CONTROL LCDBCTL0;
#define LCDBLKDIV0 0x10
#define LCDBLKDIV1 0x20
#define LCDBLKDIV2 0x40
CONTROL LCDBLKMOD0;
CONTROL LCDBLKPRE0;
CONTROL LCDBLKPRE1;
EXTERN CLASS_REG LCDBMEMCTL;
CONTROL LCDBPCTL0;
CONTROL LCDBPCTL1;
#define LCDCLRBM 1
#define LCDCLRM 2
CONTROL LCDDIV0, LCDDIV1, LCDDIV2, LCDDIV3;
CONTROL LCDON;
CONTROL LCDPRE0, LCDPRE1;
#define LOCK 1
#define LOCKA 2
#define LOCKINFO 4
#define LPM3_bits 8
#define MC1 1
CONTROL MCSM0, MCSM1, MC_1, MC_2;
CONTROL MDMCFG2, MDMCFG3, MDMCFG4;
CONTROL OFIFG;
#define OUTMOD_4 1
CONTROL P1DIR;
CONTROL P1MAP0; /* Array of registers!? */
CONTROL P1OUT;
CONTROL P1REN;
CONTROL P1SEL;
CONTROL P2DIR;
CONTROL P2IE;
CONTROL P2IES;
CONTROL P2IFG;
CONTROL P2IN;
CONTROL P2MAP0; /* Array of registers? */
CONTROL P2OUT;
CONTROL P2REN;
CONTROL P2SEL;
CONTROL P5DIR;
CONTROL P5SEL;
CONTROL PJDIR,  PJIN, PJOUT;
CONTROL PKTCTRL0;
CONTROL PKTCTRL1;
CONTROL PKTLEN;
CONTROL PMAPCTL;
CONTROL PMAPPWD;
CONTROL PMAPRECFG;
#define PMMCOREV0 1
#define PMMCOREV_3 2
CONTROL PMMCTL0_H, PMMCTL0_L;
#define PMMHPMRE 16
CONTROL PMMIFG;
#define PM_TA1CCR0A 1
#define PM_UCA0CLK 2
#define PM_UCA0SIMO 4
#define PM_UCA0SOMI 8
CONTROL REFCTL0;
#define REFMSTR 1
#define REFON 2
#define REFVSEL_0 4
#define REFVSEL_1 8
CONTROL RF1ADINB;
#define RF1ADOUT1B 32
#define RF1ADOUTB 64
CONTROL RF1AIE;
CONTROL RF1AIES;
CONTROL RF1AIFCTL1;
CONTROL RF1AIFERR;
CONTROL RF1AIFG;
CONTROL RF1AIV;
#define RF1AIV_NONE 0
#define RF1AIV_RFIFG9 1
#define RF1AIV_RFIFG10 2
CONTROL RF1AIN, RF1ADOUT0B;
CONTROL RF1AINSTR1B, RF1AINSTRB, RF1ASTATB, RFDINIFG, RFDOUTIFG, RFINSTRIFG, RFSTATIFG, RF1AINSTRW;
#define RF_REGRD 1
#define RF_REGWR 2
CONTROL FSCTRL0;
CONTROL LCDBVCTL;

#define RF_PATABWR 1
#define RF_RXFIFORD 2
#define RF_RXSTAT 4
#define RF_SFRX 8
#define RF_SFTX 16
#define RF_SIDLE 32
#define RF_SNGLREGWR 64
#define RF_SNOP 128
#define RF_SRES 256
#define RF_SRX 0x200
#define RF_STX 0x400
#define RF_SXOFF 0x800
#define RF_TXFIFOWR 0x1000
#define RF_TXSTAT 0x2000
#define RF_SPWD 0x4000
#define RF_SWOR 0x8000
CONTROL SCG0;
#define SELA__XT1CLK 1
#define SELM__DCOCLKDIV 2
#define SELS__DCOCLKDIV 4
CONTROL SFRIFG1;
#define SVMHE 1
#define SVMLE 2
#define SVMLIFG 4
#define SVMLVLRIFG 8
#define SVSHE 1
#define SVSHRVL0 2
#define SVSLE 4
#define SVSLRVL0 8
CONTROL SVSMHCTL;
#define SVSMHRRL0 32
CONTROL SVSMLCTL;
#define SVSMLDLYIFG 64
#define SVSMLRRL0 128
CONTROL TA0IV;
CONTROL TA0CCR0, TA0CCR1, TA0CCR2, TA0CCR3, TA0CCR4;
CONTROL TA0CCTL0, TA0CCTL1, TA0CCTL2, TA0CCTL3, TA0CCTL4;
CONTROL TA0CTL;
CONTROL TA0R;
CONTROL TA1CCR0, TA1CCTL0;
CONTROL TA1CTL;
CONTROL TA1R;
#define TACLR 32
#define TASSEL0 64
#define TASSEL__ACLK 128
#define TEST0 1
#define TEST1 2
#define TEST2 4
CONTROL UCA0BR0, UCA0BR1;
CONTROL UCA0CTL0, UCA0CTL1;
CONTROL UCA0TXBUF, UCA0RXBUF, UCA0IFG;
#define UCCKPH 8
#define UCMSB 16
#define UCMST 32
#define UCRXIFG 64
CONTROL UCSCTL0, UCSCTL1, UCSCTL2, UCSCTL3, UCSCTL4, UCSCTL6, UCSCTL7, UCSSEL1;
CONTROL UCSWRST, UCSYNC;
CONTROL WDTCNTCL, WDTCTL;
#define WDTHOLD 1
#define WDTIS__512K 2
#define WDTPW 4
#define WDTSSEL__ACLK 8
#define WRT 16
#define XCAP_3 32
#define XT1DRIVE_3 64
#define XT1HFOFFG 128
#define XT1LFOFFG 256
#define XT1OFF 512
#define XT2OFFG 1024
CONTROL IOCFG2;

#define __interrupt
#define LPM4_bits 0

